name: "Prod-UW2-TF-Run"
on:
  push:
    branches:
      - main
    paths:
      - Prod/us-west-2/**
  pull_request:
    branches:
      - main
    paths:
      - Prod/us-west-2/**

permissions:
  id-token: write  # Grants permission to generate a token
  contents: read   # Grants the workflow read-only access to repository contents

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      tf_actions_working_dir: './Prod/us-west-2'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
      - name: 🏗 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-west-2
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        